/**
 * Exams Reviews API
 * API for submitting and retrieving reviews for professors
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("DefaultApi", () => {
  let instance: api.DefaultApi
  beforeEach(function() {
    instance = new api.DefaultApi(config)
  });

  test("reviewsPost", () => {
    const body: api.ReviewsBody = undefined
    return expect(instance.reviewsPost(body, {})).resolves.toBe(null)
  })
  test("reviewsReviewIdDelete", () => {
    const reviewId: string = "reviewId_example"
    return expect(instance.reviewsReviewIdDelete(reviewId, {})).resolves.toBe(null)
  })
  test("reviewsReviewIdGet", () => {
    const reviewId: string = "reviewId_example"
    return expect(instance.reviewsReviewIdGet(reviewId, {})).resolves.toBe(null)
  })
  test("reviewsReviewIdPut", () => {
    const body: api.ReviewUpdate = undefined
    const reviewId: string = "reviewId_example"
    return expect(instance.reviewsReviewIdPut(body, reviewId, {})).resolves.toBe(null)
  })
})

